spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: employee-root
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees
          filters:
            - SetPath=/api/v1/employees

        - id: employee
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - StripPrefix=1
            - RewritePath=^/?(?<remaining>.*)$, /api/v1/employees/${remaining}

        - id: department-root
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments
          filters:
            - SetPath=/api/v1/departments

        - id: department
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - StripPrefix=1
            - RewritePath=^/?(?<remaining>.*)$, /api/v1/departments/${remaining}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
