spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: department
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - StripPrefix=1
        - id: employee
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
          filters:
            - StripPrefix=1

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
