logging:
  logstash:
    enabled: true
    host: localhost
    port: 5044
    appName: ${spring.application.name}

spring:
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
