services:
  db:
    image: postgres:16-alpine
    container_name: pg-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456!"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
