spring:
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: "configserver:"   # hard fail if unavailable (acceptance requirement)

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env
